"""empty message

Revision ID: 23af948656ee
Revises: 
Create Date: 2019-12-06 14:19:11.921748

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '23af948656ee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('RSVPs')
    op.drop_table('CheckIns')
    op.drop_table('Members')
    op.drop_table('Meals')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CheckIns',
    sa.Column('MealId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Email', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('Timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['Email'], ['Members.Email'], name='CheckIns_Email_fkey'),
    sa.ForeignKeyConstraint(['MealId'], ['Meals.MealId'], name='CheckIns_MealId_fkey'),
    sa.PrimaryKeyConstraint('MealId', 'Email', name='CheckIns_pkey')
    )
    op.create_table('Meals',
    sa.Column('MealId', sa.INTEGER(), server_default=sa.text('nextval(\'"Meals_MealId_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('Date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('Description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('DinnerBool', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('MealId', name='Meals_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('Members',
    sa.Column('Email', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('_Password', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('FirstName', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('LastName', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('MealAllowance', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('WeekMealsUsed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('ConfirmedEmail', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('Email', name='Members_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('RSVPs',
    sa.Column('MealId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Email', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('Timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['Email'], ['Members.Email'], name='RSVPs_Email_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['MealId'], ['Meals.MealId'], name='RSVPs_MealId_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('MealId', 'Email', name='RSVPs_pkey')
    )
    op.drop_table('test')
    # ### end Alembic commands ###
