"""empty message

Revision ID: 341cc572bdfc
Revises: 23af948656ee
Create Date: 2019-12-06 14:20:45.656388

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '341cc572bdfc'
down_revision = '23af948656ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ##
    op.drop_table('RSVP')
    op.drop_table('CheckIn')
    op.drop_table('Member')
    op.drop_table('Meal')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Meal',
    sa.Column('MealId', sa.INTEGER(), server_default=sa.text('nextval(\'"Meal_MealId_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('Date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('Description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('DinnerBool', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('MealId', name='Meal_pkey'),
    postgresql_ignore_search_path=False
    )
    
    op.create_table('Member',
    sa.Column('Email', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('_Password', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('FirstName', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('LastName', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('MealAllowance', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('WeekMealsUsed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('ConfirmedEmail', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('Email', name='Member_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('CheckIn',
    sa.Column('MealId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Email', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('Timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['Email'], ['Member.Email'], name='CheckIn_Email_fkey'),
    sa.ForeignKeyConstraint(['MealId'], ['Meal.MealId'], name='CheckIn_MealId_fkey'),
    sa.PrimaryKeyConstraint('MealId', 'Email', name='CheckIn_pkey')
    )
    op.create_table('RSVP',
    sa.Column('MealId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Email', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('Timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['Email'], ['Member.Email'], name='RSVP_Email_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['MealId'], ['Meal.MealId'], name='RSVP_MealId_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('MealId', 'Email', name='RSVP_pkey')
    )
    # ### end Alembic commands ###
