"""empty message

Revision ID: f86a43793eee
Revises: 341cc572bdfc
Create Date: 2019-12-09 20:08:48.266085

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f86a43793eee'
down_revision = '341cc572bdfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Admin')
    op.drop_table('RSVP')
    op.drop_table('Meal')
    op.drop_table('CheckIn')
    op.drop_table('test')
    op.drop_table('Member')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Member',
    sa.Column('Email', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('_Password', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('FirstName', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('LastName', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('MealAllowance', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('WeekMealsUsed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('ConfirmedEmail', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('Email', name='Member_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('test',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='test_pkey')
    )
    op.create_table('CheckIn',
    sa.Column('MealId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Email', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('Timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['Email'], ['Member.Email'], name='CheckIn_Email_fkey'),
    sa.ForeignKeyConstraint(['MealId'], ['Meal.MealId'], name='CheckIn_MealId_fkey'),
    sa.PrimaryKeyConstraint('MealId', 'Email', name='CheckIn_pkey')
    )
    op.create_table('Meal',
    sa.Column('MealId', sa.INTEGER(), server_default=sa.text('nextval(\'"Meal_MealId_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('Date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('Description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('DinnerBool', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('MealId', name='Meal_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('RSVP',
    sa.Column('MealId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Email', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('Timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['Email'], ['Member.Email'], name='RSVP_Email_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['MealId'], ['Meal.MealId'], name='RSVP_MealId_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('MealId', 'Email', name='RSVP_pkey')
    )
    op.create_table('Admin',
    sa.Column('AdminId', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('Email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('FirstName', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('LastName', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('MealAllowance', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('WeekMealsUsed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('ConfirmedEmail', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['Email'], ['Member.Email'], name='Admin_Email_fkey'),
    sa.PrimaryKeyConstraint('AdminId', 'Email', name='Admin_pkey')
    )
    # ### end Alembic commands ###
